### ISSUE TITLE
Exception on not being logged in instead of a reasonable message

### ISSUE THREAD

**Issue by JoeLudwig** [webaverse/xrpackage-cli#4]
(and the command name is wrong at the top)

This should print "you are not logged in" or something like that instead of a stack trace. "xrpk privatekey" has the same issue, presumably for the same reason.

```
E:\homedev\foo>xrpk whoami
cli.js whoami

print logged in address

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: ENOENT: no such file or directory, open 'C:\Users\Joe\.xrpackage'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at getKs (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:72:23)
    at Object.handler (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:188:22)
    at Object.runCommand (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\yargs\lib\command.js:240:40)
    at Object.parseArgs [as _parseArgs] (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\yargs\yargs.js:1154:41)
    at Object.get [as argv] (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\yargs\yargs.js:1088:21)
    at Object.<anonymous> (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:696:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Joe\\.xrpackage'
}
```

**Comment by avaer** [comment]
Yeah we should definitely check for the dotfile.

**Comment by avaer** [comment]
Should print not logged in messages now.
