### ISSUE TITLE
"xrpk build" usage should talk about what manifest.json is

### ISSUE THREAD

**Issue by JoeLudwig** [webaverse/xrpackage-cli#6]
I tried to build a directory expecting that to package up all the files in the directory.  Instead I got an error about manifest.json being missing. That error was expressed in the form of an exception, which should probably be more user-friendly.

It should also tell me what a manifest file is and how to make one.

```
E:\homedev\foo>xrpk build dist foo_gadget
cli.js build [input] [output]

build xrpackage .wbn from [input] and write to [output]

Positionals:
  input   input file to build
  output  output file to write

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: ENOENT: no such file or directory, open 'E:\homedev\foo\dist\manifest.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at _detectType (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:542:22)
    at _detectType (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:556:11)
    at Object.handler (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:562:5)
    at Object.runCommand (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\yargs\lib\command.js:240:40)
    at Object.parseArgs [as _parseArgs] (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\yargs\yargs.js:1154:41)
    at Object.get [as argv] (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\yargs\yargs.js:1088:21)
    at Object.<anonymous> (C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\cli.js:696:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\homedev\\foo\\dist\\manifest.json'
}
```

**Comment by avaer** [comment]
This is a really good idea.

**Comment by avaer** [comment]
Recommends using `xrpk init` now.
